#!/usr/bin/env python3

import sys
import os
import csv
import json
import pprint
from matplotlib import pyplot as plt
from decimal import Decimal


pp = pprint.PrettyPrinter(indent=4)
csv_path = sys.argv[1]
if csv_path == None:
    print('You must provide CSV_PATH arg')
    sys.exit(1)

csv_exists = os.path.isfile(csv_path)
if not csv_exists:
    print(f'Unable to find csv: {csv_path}')
    sys.exit(1)


def extract_price(car):
    if 'price' in car and len(car['price']) > 2:
        try:
            return Decimal(car['price'].strip('$'))
        except:
            print('!!!!!!!')
            print(car['price'])
    return None

def extract_mileage(meta_json):
    meta = json.loads(meta_json)
    if 'mileage' in meta:
        return meta['mileage']
    if 'odometer' in meta:
        return meta['odometer']
    return None

x_price = []
y_mileage = []

with open(csv_path) as csv_file:
    csv_reader = csv.reader(csv_file, delimiter=',')
    line_count = 0
    data = []
    for row in csv_reader:
        line_count += 1
        if line_count == 1:
            header_row = row
            print(f'Column names are {", ".join(row)}')
        else:
            line_count += 1
            car = (dict(zip(header_row, row)))
            price = extract_price(car)
            if price == None:
                pass
            mileage = extract_mileage(car['meta'])
            if mileage == None:
                pass
            x_price.append(price)
            y_mileage.append(mileage)
            # data.append((price, mileage))

if len(x_price) == len(y_mileage):
    print(f'{len(x_price)} pairs found')
    plt.scatter(x_price, y_mileage)
    plt.show()
